### ISSUE TITLE
support exporting several application logs to STDOUT

### ISSUE THREAD

**Issue by moabu** [JanssenProject/docker-jans-auth-server#75]
**Is your feature request related to a problem? Please describe.**

Some issues arise in scrapping logs. The only log pointed to STDOUT is the auth-server log.

**Describe the solution you'd like**

Add the ability to point any number of logs to STDOUT. This should be in the form of a list taking into the logs names. i.e `APPLICATION_LOGS_EXPORTED_STDOUT: ["jans-auth_script.log", "jans-auth.log"]`

**Comment by iromli** [comment]
@moabu The following names are mapped to log files:

```
FILE: jans-auth.log
JANS_AUTH_HTTP_REQUEST_RESPONSE_FILE: http_request_response.log
JANS_AUTH_PERSISTENCE_FILE: jans-auth_persistence.log
JANS_AUTH_PERSISTENCE_DURATION_FILE: jans-auth_persistence_duration.log
JANS_AUTH_PERSISTENCE_LDAP_STATISTICS_FILE: jans-auth_persistence_ldap_statistics.log
JANS_AUTH_SCRIPT_LOG_FILE: jans-auth_script.log
JANS_AUTH_AUDIT_LOG_FILE: jans-auth_audit.log
```

Instead of defining list for log names, I'm proposing to have each env var for its log redirect/target and level, i.e.:

```
CN_AUTH_LOG_TARGET: STDOUT|FILE
CN_AUTH_LOG_LEVEL: INFO|WARN|DEBUG
CN_AUTH_PERSISTENCE_LOG_TARGET: STDOUT|FILE
CN_AUTH_PERSISTENCE_LOG_LEVEL: INFO|WARN|DEBUG
```

The advantages:
- users don't need to remember/know which log files are supported by the logic
- users can change the log level (for debugging purpose, etc)
